### PR TITLE
Add synthesis flow for Black Parrot design on ASIC PDK

### PR DESCRIPTION
**Pull request by robertszczepanski**
This PR adds a synthesis flow for BlackParrot multicore design. It uses [OpenROAD flow scripts](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/) and targets Nangate45 PDK but should be easily extendable to more platforms.

### CODE REVIEW

**Comment by alaindargelas** [comment]
@robertszczepanski , there is something incorrect in the design setup:

...
[NTE:EL0508] Nb Top level modules: 176.
...

There should be only 1 top-level module. This is not going to work until this is resolved.

**Comment by alaindargelas** [comment]
Closed by error. Reopened.

**Comment by robertszczepanski** [comment]
CI failed due to lack of RAM for BlackParrot FPGA synthesis. This is a similiar issue to the one that happens in https://github.com/chipsalliance/synlig/pull/1941 recently. I can see that this flow operates on a RAM close to its limits even on main branch CI ([see "RAM usage (100% = 15.64 GB)"](https://github.com/chipsalliance/synlig/actions/runs/6324778186/job/17175507115)) so I increased its resources in a separate commit.

**Comment by alaindargelas** [comment]
Please note the same multi top level module issue is also present in the sv-tests Black parrot multi core designs, please fix the design setup there too when you get a chance.

**Pull request merged**
