### PR TITLE
drop unicode separators in Makefiles

### PR DESCRIPTION
**Pull request by kgugala**
This PR drops unicode sections separators as they may not be properly handled in older terminal emulators

### CODE REVIEW

**Review by hzeller — APPROVED** [review]
LGTM

**Comment by hzeller** [comment]
I would also be worried about Unicode block characters (Such as `▌`) around the [print variable section](https://github.com/chipsalliance/synlig/blob/dd28e6ddc345ec098597382204085cdc15a11ac3/Makefile#L223-L231).
That could explain #2104

**Comment by pgielda** [comment]
+1 to get rid of the block as well. I suggest replacing with good old "|" ;)

**Comment by pgielda** [comment]
(I doubt its the reason for #2104 but who knows, it Centos, everything is possible)

**Pull request merged**
