### PR TITLE
Patch `yosys-config` to report accurate paths

### LINKED ISSUE #2164: `yosys-config` reports incorrect paths in prebuilt binaries
`yosys-config` reports paths that are baked-in at build time. In the prebuilt releases generated on GitHub, all paths are prefixed with `/root/synlig/synlig/out/release`, which makes the `yosys-config` bundled with Synlig nonfunctional unless the user extracts the archive in exactly that path.

[`oss-cad-suite` overcomes this problem by patching `yosys-config`](https://github.com/YosysHQ/oss-cad-suite-build/blob/f41b9ae59c6afe323b41a069da48c3835f0846b0/scripts/package-linux.sh#L248) (replacing the original build path with a path relative to `yosys-config`'s location). Perhaps something similar could be included in Synlig, either in the main build systems (Make/CMake) or at least in the GitHub workflow that generates the prebuilt binaries.

Ideally, this modification would be included in Yosys's build system, but [the way `yosys-config` is currently generated](https://github.com/YosysHQ/yosys/blob/031ad38b5cc2410823089e1990cd68694a4a9bb3/Makefile#L793) makes it quite difficult since external library include paths can't be easily separated from Yosys's own at that point in the Makefile.

### PR DESCRIPTION
**Pull request by aWZHY0yQH81uOYvH**
Fixes #2164; see it for reasoning.

I only added the script to the GitHub builds since that's where the problem is most likely to manifest itself. Users building from source will likely specify the final installation path at compile time so this patch won't be necessary.

<details>
<summary>Patched yosys-config</summary>

```bash
#!/usr/bin/env bash
install_prefix="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")/..")"

help() {
	{
		echo ""
		echo "Usage: $0 [--exec] [--prefix pf] args.."
		echo "       $0 --build modname.so cppsources.."
		echo ""
		echo "Replacement args:"
		echo "    --cxx         c++"
		echo "    --cxxflags    $( echo '-Wall -Wextra -ggdb -I"$install_prefix//share/yosys/include" -MD -MP -D_YOSYS_ -fPIC -I"$install_prefix"//include -std=c++11 -Os -DYOSYS_ENABLE_READLINE -DYOSYS_ENABLE_PLUGINS -DYOSYS_ENABLE_GLOB -DYOSYS_ENABLE_ZLIB -I/usr/include/tcl8.6 -DYOSYS_ENABLE_TCL -DYOSYS_ENABLE_ABC -DYOSYS_ENABLE_COVER' | fmt -w60 | sed ':a;N;$!ba;s/\n/ \\\n                      /g' )"
		echo "    --ldflags     -rdynamic"
		echo "    --ldlibs      -lstdc++ -lm -lrt -lreadline -lffi -ldl -lz -ltcl8.6 -ltclstub8.6"
		echo "    --bindir      "$install_prefix"//bin"
		echo "    --datdir      "$install_prefix"//share/yosys"
		echo ""
		echo "All other args are passed through as they are."
		echo ""
		echo "Use --exec to call a command instead of generating output. Example usage:"
		echo ""
		echo "  $0 --exec --cxx --cxxflags --ldflags -o plugin.so -shared plugin.cc --ldlibs"
		echo ""
		echo "The above command can be abbreviated as:"
		echo ""
		echo "  $0 --build plugin.so plugin.cc"
		echo ""
		echo "Use --prefix to change the prefix for the special args from '--' to"
		echo "something else. Example:"
		echo ""
		echo "  $0 --prefix @ bindir: @bindir"
		echo ""
		echo "The args --bindir and --datdir can be directly followed by a slash and"
		echo "additional text. Example:"
		echo ""
		echo "  $0 --datdir/simlib.v"
		echo ""
	} >&2
	exit 1
}

if [ $# -eq 0 ]; then
	help
fi

if [ "$1" == "--build" ]; then
	modname="$2"; shift 2
	set -- --exec --cxx --cxxflags --ldflags -o "$modname" -shared "$@" --ldlibs
fi

prefix="--"
get_prefix=false
exec_mode=false
declare -a tokens=()

for opt; do
	if $get_prefix; then
		prefix="$opt"
		get_prefix=false
		continue
	fi
	case "$opt" in
		"$prefix"cxx)
			tokens=( "${tokens[@]}"  c++       ) ;;
		"$prefix"cxxflags)
			tokens=( "${tokens[@]}"  -Wall -Wextra -ggdb -I"$install_prefix//share/yosys/include" -MD -MP -D_YOSYS_ -fPIC -I"$install_prefix"//include -std=c++11 -Os -DYOSYS_ENABLE_READLINE -DYOSYS_ENABLE_PLUGINS -DYOSYS_ENABLE_GLOB -DYOSYS_ENABLE_ZLIB -I/usr/include/tcl8.6 -DYOSYS_ENABLE_TCL -DYOSYS_ENABLE_ABC -DYOSYS_ENABLE_COVER  ) ;;
		"$prefix"ldflags)
			tokens=( "${tokens[@]}"  -rdynamic   ) ;;
		"$prefix"ldlibs)
			tokens=( "${tokens[@]}"  -lstdc++ -lm -lrt -lreadline -lffi -ldl -lz -ltcl8.6 -ltclstub8.6    ) ;;
		"$prefix"bindir)
			tokens=( "${tokens[@]}" "$install_prefix"'//bin'   ) ;;
		"$prefix"datdir)
			tokens=( "${tokens[@]}" "$install_prefix"'//share/yosys'   ) ;;
		"$prefix"bindir/*)
			tokens=( "${tokens[@]}" "$install_prefix"'//bin'"${opt#${prefix}bindir}" ) ;;
		"$prefix"datdir/*)
			tokens=( "${tokens[@]}" "$install_prefix"'//share/yosys'"${opt#${prefix}datdir}" ) ;;
		--help|-\?|-h)
			if [ ${#tokens[@]} -eq 0 ]; then
				help
			else
				tokens=( "${tokens[@]}" "$opt" )
			fi ;;
		--exec)
			if [ ${#tokens[@]} -eq 0 ]; then
				exec_mode=true
			else
				tokens=( "${tokens[@]}" "$opt" )
			fi ;;
		--prefix)
			if [ ${#tokens[@]} -eq 0 ]; then
				get_prefix=true
			else
				tokens=( "${tokens[@]}" "$opt" )
			fi ;;
		*)
			tokens=( "${tokens[@]}" "$opt" )
	esac
done

if $exec_mode; then
	exec "${tokens[@]}"
fi

echo "${tokens[@]}"
exit 0
```

</details>

<details>
<summary>diff</summary>

```diff
@@ -1,4 +1,5 @@
 #!/usr/bin/env bash
+install_prefix="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")/..")"
 
 help() {
 	{
@@ -8,11 +9,11 @@
 		echo ""
 		echo "Replacement args:"
 		echo "    --cxx         g++"
-		echo "    --cxxflags    $( echo '-Wall -Wextra -ggdb -I"/root/synlig/synlig/out/release//share/yosys/include" -MD -MP -D_YOSYS_ -fPIC -I/root/synlig/synlig/out/release//include -std=c++11 -Os -DYOSYS_ENABLE_READLINE -DYOSYS_ENABLE_PLUGINS -DYOSYS_ENABLE_GLOB -DYOSYS_ENABLE_ZLIB -I/usr/include/tcl8.6 -DYOSYS_ENABLE_TCL -DYOSYS_ENABLE_ABC -DYOSYS_ENABLE_COVER' | fmt -w60 | sed ':a;N;$!ba;s/\n/ \\\n                      /g' )"
+		echo "    --cxxflags    $( echo '-Wall -Wextra -ggdb -I"$install_prefix//share/yosys/include" -MD -MP -D_YOSYS_ -fPIC -I"$install_prefix"//include -std=c++11 -Os -DYOSYS_ENABLE_READLINE -DYOSYS_ENABLE_PLUGINS -DYOSYS_ENABLE_GLOB -DYOSYS_ENABLE_ZLIB -I/usr/include/tcl8.6 -DYOSYS_ENABLE_TCL -DYOSYS_ENABLE_ABC -DYOSYS_ENABLE_COVER' | fmt -w60 | sed ':a;N;$!ba;s/\n/ \\\n                      /g' )"
 		echo "    --ldflags     -rdynamic"
 		echo "    --ldlibs      -lstdc++ -lm -lrt -lreadline -lffi -ldl -lz -ltcl8.6 -ltclstub8.6"
-		echo "    --bindir      /root/synlig/synlig/out/release//bin"
-		echo "    --datdir      /root/synlig/synlig/out/release//share/yosys"
+		echo "    --bindir      "$install_prefix"//bin"
+		echo "    --datdir      "$install_prefix"//share/yosys"
 		echo ""
 		echo "All other args are passed through as they are."
 		echo ""
@@ -62,19 +63,19 @@
 		"$prefix"cxx)
 			tokens=( "${tokens[@]}"  g++       ) ;;
 		"$prefix"cxxflags)
-			tokens=( "${tokens[@]}"  -Wall -Wextra -ggdb -I"/root/synlig/synlig/out/release//share/yosys/include" -MD -MP -D_YOSYS_ -fPIC -I/root/synlig/synlig/out/release//include -std=c++11 -Os -DYOSYS_ENABLE_READLINE -DYOSYS_ENABLE_PLUGINS -DYOSYS_ENABLE_GLOB -DYOSYS_ENABLE_ZLIB -I/usr/include/tcl8.6 -DYOSYS_ENABLE_TCL -DYOSYS_ENABLE_ABC -DYOSYS_ENABLE_COVER  ) ;;
+			tokens=( "${tokens[@]}"  -Wall -Wextra -ggdb -I"$install_prefix//share/yosys/include" -MD -MP -D_YOSYS_ -fPIC -I"$install_prefix"//include -std=c++11 -Os -DYOSYS_ENABLE_READLINE -DYOSYS_ENABLE_PLUGINS -DYOSYS_ENABLE_GLOB -DYOSYS_ENABLE_ZLIB -I/usr/include/tcl8.6 -DYOSYS_ENABLE_TCL -DYOSYS_ENABLE_ABC -DYOSYS_ENABLE_COVER  ) ;;
 		"$prefix"ldflags)
 			tokens=( "${tokens[@]}"  -rdynamic   ) ;;
 		"$prefix"ldlibs)
 			tokens=( "${tokens[@]}"  -lstdc++ -lm -lrt -lreadline -lffi -ldl -lz -ltcl8.6 -ltclstub8.6    ) ;;
 		"$prefix"bindir)
-			tokens=( "${tokens[@]}" '/root/synlig/synlig/out/release//bin'   ) ;;
+			tokens=( "${tokens[@]}" "$install_prefix"'//bin'   ) ;;
 		"$prefix"datdir)
-			tokens=( "${tokens[@]}" '/root/synlig/synlig/out/release//share/yosys'   ) ;;
+			tokens=( "${tokens[@]}" "$install_prefix"'//share/yosys'   ) ;;
 		"$prefix"bindir/*)
-			tokens=( "${tokens[@]}" '/root/synlig/synlig/out/release//bin'"${opt#${prefix}bindir}" ) ;;
+			tokens=( "${tokens[@]}" "$install_prefix"'//bin'"${opt#${prefix}bindir}" ) ;;
 		"$prefix"datdir/*)
-			tokens=( "${tokens[@]}" '/root/synlig/synlig/out/release//share/yosys'"${opt#${prefix}datdir}" ) ;;
+			tokens=( "${tokens[@]}" "$install_prefix"'//share/yosys'"${opt#${prefix}datdir}" ) ;;
 		--help|-\?|-h)
 			if [ ${#tokens[@]} -eq 0 ]; then
 				help
```

</details>

### CODE REVIEW

**Comment by aWZHY0yQH81uOYvH** [comment]
Tail of failing (4.4GB!) Opentitan synthesis log:

<details>
<summary>Log</summary>

```
2023-11-25T02:09:43.2712431Z Routing Is Done.
2023-11-25T02:09:43.2713007Z 64 Infos, 165 Warnings, 11 Critical Warnings and 0 Errors encountered.
2023-11-25T02:09:43.2713659Z route_design completed successfully
2023-11-25T02:09:43.2714569Z route_design: Time (s): cpu = 00:02:45 ; elapsed = 00:01:31 . Memory (MB): peak = 2677.055 ; gain = 223.613 ; free physical = 51925 ; free virtual = 58660
2023-11-25T02:09:43.2715548Z Writing placer database...
2023-11-25T02:09:43.2716013Z Writing XDEF routing.
2023-11-25T02:09:43.2716486Z Writing XDEF routing logical nets.
2023-11-25T02:09:43.2716994Z Writing XDEF routing special nets.
2023-11-25T02:09:43.2717977Z Write XDEF Complete: Time (s): cpu = 00:00:04 ; elapsed = 00:00:02 . Memory (MB): peak = 2701.047 ; gain = 0.000 ; free physical = 51876 ; free virtual = 58653
2023-11-25T02:09:43.2719969Z INFO: [Common 17-1381] The checkpoint '/root/synlig/synlig/tests/build/lowrisc_systems_top_earlgrey_nexysvideo_0.1/synth-vivado/lowrisc_systems_top_earlgrey_nexysvideo_0.1.runs/impl_1/lowrisc_systems_top_earlgrey_nexysvideo_0.1_routed.dcp' has been generated.
2023-11-25T02:09:43.2722157Z Command: report_drc -file lowrisc_systems_top_earlgrey_nexysvideo_0.1_drc_routed.rpt -pb lowrisc_systems_top_earlgrey_nexysvideo_0.1_drc_routed.pb -rpx lowrisc_systems_top_earlgrey_nexysvideo_0.1_drc_routed.rpx
2023-11-25T02:09:43.2723411Z INFO: [DRC 23-27] Running DRC with 8 threads
2023-11-25T02:09:43.2724996Z INFO: [Coretcl 2-168] The results of DRC are in file /root/synlig/synlig/tests/build/lowrisc_systems_top_earlgrey_nexysvideo_0.1/synth-vivado/lowrisc_systems_top_earlgrey_nexysvideo_0.1.runs/impl_1/lowrisc_systems_top_earlgrey_nexysvideo_0.1_drc_routed.rpt.
2023-11-25T02:09:43.2726404Z report_drc completed successfully
2023-11-25T02:09:43.2727561Z Command: report_methodology -file lowrisc_systems_top_earlgrey_nexysvideo_0.1_methodology_drc_routed.rpt -rpx lowrisc_systems_top_earlgrey_nexysvideo_0.1_methodology_drc_routed.rpx
2023-11-25T02:09:43.2728793Z INFO: [Timing 38-35] Done setting XDC timing constraints.
2023-11-25T02:09:43.2729497Z INFO: [DRC 23-133] Running Methodology with 8 threads
2023-11-25T02:09:43.2730335Z /opt/Xilinx/Vivado/2017.2/bin/rdiArgs.sh: line 179:  8076 Segmentation fault      "$RDI_PROG" "$@"
2023-11-25T02:09:43.2731122Z [Sat Nov 25 01:09:33 2023] impl_1 finished
2023-11-25T02:09:43.2760594Z wait_on_run: Time (s): cpu = 00:00:00.12 ; elapsed = 00:04:11 . Memory (MB): peak = 1067.352 ; gain = 0.000 ; free physical = 53244 ; free virtual = 59988
2023-11-25T02:09:43.2761980Z Bitstream generation completed
2023-11-25T02:09:43.2762590Z ERROR: Implementation and bitstream generation step failed.
2023-11-25T02:09:43.2763462Z INFO: [Common 17-206] Exiting Vivado at Sat Nov 25 01:09:33 2023...
2023-11-25T02:09:43.2764520Z make[1]: Leaving directory '/root/synlig/synlig/tests/build/lowrisc_systems_top_earlgrey_nexysvideo_0.1/synth-vivado'
2023-11-25T02:09:43.2765324Z 
2023-11-25T02:09:43.2766231Z ERROR: make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
2023-11-25T02:09:43.2767166Z make[1]: *** [Makefile:20: lowrisc_systems_top_earlgrey_nexysvideo_0.1.bit] Error 1
2023-11-25T02:09:43.2767838Z 
2023-11-25T02:09:43.2768577Z ERROR: Failed to build lowrisc:systems:top_earlgrey_nexysvideo:0.1 : '['make']' exited with an error: 2
2023-11-25T02:09:43.2769693Z make: *** [opentitan/Makefile.in:19: uhdm/yosys/synth-opentitan-build] Error 1
2023-11-25T02:09:43.2770949Z Got file without file_type, skipping it: {'name': 'util/check_tool_requirements.py', 'core': 'lowrisc:tool:check_tool_requirements:0.1'}
2023-11-25T02:09:43.2772388Z Got file without file_type, skipping it: {'name': 'tool_requirements.py', 'core': 'lowrisc:tool:check_tool_requirements:0.1'}
2023-11-25T02:09:43.2773185Z 
2023-11-25T02:09:43.2773692Z make: Leaving directory '/root/synlig/synlig/tests'
2023-11-25T02:09:43.3709755Z ##[error]Process completed with exit code 2.
```

</details>

Appears to be Vivado blowing up?

**Comment by tgorochowik** [comment]
Seems to have been random. The CI passed after restarting this job.

**Review by tgorochowik — COMMENTED** [review]
The change looks reasonable to me. Could you please propose a new CI job that would verify that it works as expected?

**Comment by aWZHY0yQH81uOYvH** [comment]
The check could be as simple as

```shell
mv out /tmp
ls $(/tmp/out/current/bin/yosys-config --datdir) > /dev/null
```

The original install directory doesn't exist anymore, so if `ls` exits zero, the script must have returned an updated path.

I don't really see a good place for this, however. Any suggestions?

**Comment by tgorochowik** [comment]
What I meant is that we have a test for the packaged yosys here:
https://github.com/chipsalliance/synlig/blob/main/.github/workflows/main.yml#L452 (it downloads the artifacts, install the plugin to a yosys installed from a distro package).

With your change, we should be able to use the full artifact package (that includes yosys) install it to an arbitrary directory, and prove that it works.
I think that this should be tested with a separate CI step to make sure it actually works and continues to work as we go forward.

**Comment by aWZHY0yQH81uOYvH** [comment]
@tgorochowik I didn't realize such a test didn't exist before. How does the one I added look?

**Review by tgorochowik — COMMENTED** [review]
Looks great, thanks!

One nitpick, in the CI logs you can see:
```
yosys-config reports data directory is /root/synlig/synlig/binaries-debian/out/release//share/yosys
```

There is a double `/` before `/share/yosys`.

It's not a big problem, but it'd be better to clean this up

**Comment by aWZHY0yQH81uOYvH** [comment]
Yes, that double slash was there before this change and seems to come from somewhere else in the build process. I was hesitant to add a trailing `/` in the `sed` commands in `patch_yosys_config.sh` in case it was ever removed.

**Review by tgorochowik — APPROVED** [review]
Fair enough, let's handle this issue separately. Thank you for the contribution!

**Comment by aWZHY0yQH81uOYvH** [comment]
The double-slash issue can be fixed with the following change
```diff
diff --git a/buildconfig.mk b/buildconfig.mk
index eb86659..b64b814 100644
--- a/buildconfig.mk
+++ b/buildconfig.mk
@@ -11,8 +11,8 @@
 CFG_BUILD_TYPE := release
 
 # Base directory for all build outputs.
-CFG_BUILD_DIR = build/${CFG_BUILD_TYPE}/
-CFG_OUT_DIR = out/${CFG_BUILD_TYPE}/
+CFG_BUILD_DIR = build/${CFG_BUILD_TYPE}
+CFG_OUT_DIR = out/${CFG_BUILD_TYPE}
 
 # Basic build tools
 CC       ?= cc
```

Builds fine on my machine; should verify those trailing slashes aren't needed anywhere in the CI checks though.

I can do another tiny PR if we care.

**Comment by tgorochowik** [comment]
Sure, please do!

**Pull request merged**
