### PR TITLE
Adapt to Surelog API change

### PR DESCRIPTION
**Pull request by alaindargelas**

### CODE REVIEW

**Comment by kgugala** [comment]
does this really do anything with signed/unsigned? looking at the changes it seems to be only adapting the code for Surelog API changes

**Comment by alaindargelas** [comment]
The real change is in Surelog, critical warning and propagation of signage

**Comment by hzeller** [comment]
Would it be good to also update the [Synlig version](https://github.com/chipsalliance/synlig/blob/main/CMakeLists.txt#L12) to match the Surelog/UHDM versions it is compatible with ?

**Comment by alain-rs** [comment]
The cmake build does that. But this merge happened out of order.
The stable_rs branch is up to date with versions

**Pull request merged**
