### PR TITLE
update surelog const propagation

### PR DESCRIPTION
**Pull request by alaindargelas**

### CODE REVIEW

**Comment by alaindargelas** [comment]
@kbieganski , if this pass, please merge, it fixes #1994

**Comment by kgugala** [comment]
@alaindargelas you can also find all the logs in the CI artifacts (those are visible in the [summary page](https://github.com/chipsalliance/synlig/actions/runs/6294719168?pr=2009))

the logs from the failed parsing tests can be found [here](https://github.com/chipsalliance/synlig/suites/16515808820/artifacts/943503088)

**Comment by mglb** [comment]
> I can't find which test fails. Also not sure if the instructions to rerun is the same as last time: make -C tests uhdm/yosys/test-ast TEST=simple_tests/FunctionDeclInModuleUsedInParamAssign PARSER=surelog

https://github.com/chipsalliance/synlig/actions/runs/6294719168/attempts/1#summary-17087574634

`simple_cs_registers`

Logs are in `parsing_read-systemverilog_logs` artifact.
Log browser on github contains only brief info because it has problems with displaying and browsing very long outputs.

**Comment by alaindargelas** [comment]
Thanks, how do I rerun this particular test with asan check?
I'm still trying to figure it out.

**Comment by kbieganski** [comment]
Build the binaries with `ENABLE_ASAN=1`:
```
make -rR -j$(nproc) -Oline -f build_binaries.mk ENABLE_ASAN=1 \
    install-surelog install-yosys install-plugin  
```
then run the test:
```
make -C tests uhdm/yosys/test-ast TEST=simple_tests/simple_cs_registers PARSER=surelog
```

**Review by kbieganski — APPROVED** [review]

**Comment by alaindargelas** [comment]
@kbieganski looks like it is passing, please merge.

**Pull request merged**
