### PR TITLE
Surelog parses more attributes for nets, modules, while at it support formal at…

### PR DESCRIPTION
**Pull request by alaindargelas**
…tributes

### CODE REVIEW

**Comment by kamilrakoczy** [comment]
The change itself looks ok to me, but [one of the formal verification tests](https://github.com/YosysHQ/yosys/blob/main/tests/simple_abc9/abc9.v) now fails to parse:
```
yosys:simple_abc9/abc9.v resulted with: PLUGIN_READ_FAIL, but expected result was: UNMATCHED_MODULE [ERROR]
```
Could you please check this?

**Comment by alaindargelas** [comment]
Fixed with whitebox attr support:
https://github.com/chipsalliance/synlig/pull/2605/files

**Comment by alaindargelas** [comment]
@kamilrakoczy this is passing, modulo one of the actions that failed.

blackbox attribute is now correctly handled, even if not the only attribute in a list of attributes (Which is the main fix here).

**Comment by alaindargelas** [comment]
All fixed

**Review by kamilrakoczy — APPROVED** [review]

**Comment by kamilrakoczy** [comment]
LGTM, thanks.

**Pull request merged**
